#ifndef _LIB_PARAM_H_
#define _LIB_PARAM_H_

#define SEND_DATA_LEN 120
#define RECEIVE_DATA_LEN 120
#define INT_ERROR -1

#define SHELD_TYPE 0x00
#define VERSION 0x00

#define MOTOR_RAM_LENGTH  74
#define MOTOR_ROM_LENGTH 37
#define MOTOR_SERIAL_LENGTH 111
#define MOTOR_SEND_SERIAL_LENGTH 99

#define DEFAULT_DATA_COUNT 4
#define DEFAULT_ID 0

#define MOTOR_BORD_DATA_LEN 52 //motordata:12 * 4 + lpf:2 + ui:2 = 52//ui:PRINT|LED
#define MOTOR_BORD_MAX_NUM 10

//motor default data//
#define DEFAULT_SHORT_FLAG 0x00
//ram//
#define DEFAULT_ROTATE_SPEED_L 0x00
#define DEFAULT_ROTATE_SPEED_H 0x00
#define DEFAULT_ROTATE_PWR 0x00
#define DEFAULT_BRAKE_PWR 0xFF
#define DEFAULT_ACTIVATE_CUR 0b0
#define DEFAULT_ACTIVATE_ENC 0b0
#define DEFAULT_ENC_DIRECTION 0b0
#define DEFAULT_LIB_LED 0x00
#define DEFAULT_NOW_SPEED_L 0x00
#define DEFAULT_NOW_SPEED_H 0x00
#define DEFAULT_NOW_PWR 0x00
//rom//
#define TARTAR_VERSION 0x00
#define SHIELD_VERSION 0x00
#define DEFAULT_ACTIVATE_BRAKE 0b0
#define DEFAULT_ROTATE_WITH_BRAKE 0b0
#define DEFAULT_ROTATE_DIRECTION 0b0
#define DEFAULT_ADJUST_PWR 1.0
#define DEFAULT_LOWER_LIMIT 0
#define DEFAULT_ENC_P 1.0
#define DEFAULT_ENC_I 0.0
#define DEFAULT_ENC_D 0.0
#define DEFAULT_CUR_P 1.0
#define DEFAULT_CUR_I 0.0
#define DEFAULT_CUR_D 0.0
#define DEFAULT_LPF_K 0.0
#define DEFAULT_LPF_T 1.0
#endif
