name=TartarConnect
version=1.0.0
author=cathodegnd
maintainer=cathodegnd
sentence=RS485 communication library for controlling motor driver boards
paragraph=Control motor driver boards via RS485 communication.
category=Communication
architectures=*